include::header.adoc[]

:title: Assignment 7: Some Assembly Required
:Author Initials: ASN
:Date:    2020-08-15
:Revision: 0.1
:ASST: A07

= {title}

**Due (Hardcopy) Tuesday, March 17th In class**

**This is a written assignment, not a coding assignment!**

The goals for this assignment are:

* Understand basic x86_64 assembly instructions, especially memory addressing
* Visualize the execution of x86_64 assembly instructions


:sectnums:

= Operand practice

[cols="1a,1a"]
|===
|Suppose memory has the following values:
[cols="1,1"]
!===
!Address ! Value
!0xf08 ! 0x10
!0xf0a ! 0x3c
!0xf0c ! 0x14
!0xf0e ! 0x04
!0xf10 ! 0x34
!0xf12 ! 0xe4
!===

|And suppose our registers have the following values:
[cols="1,1"]
!===
!Register ! Value
!%rax ! 0xf08
!%rbx ! 0x44
!%rsi ! 0x08
!%r8  ! 0x01
!===
|===

++++
<div class="pagebreak"></div>
++++

Fill in the following table with the corresponding form, translation, and 
value for each of the given operands.

[cols="1,1,4,1"]
|===
|Operand
|Form
|Translation
|Value

|%rax
|
|{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
|

|0x4(%rax)
|
|{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
|

|0x4(%rax, %r8, 4)
|
|{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
|

|0xf00(,%rsi,2)
|
|{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
|
|===

++++
<div class="pagebreak"></div>
++++

= The answer is 42

Recall the following example from class and
link:https://diveintosystems.org/book/C7-x86_64/functions.html[_Dive into
Systems_]. This mysterious program reliably produces the output `42`. In this
question, you will trace the assembly to understand why.

[source]
----
#include <stdio.h>

int assign(void) {
    int y = 40;
    return y;
}

int adder(void) {
    int a;
    return a + 2;
}

int main(void) {
    int x;
    assign();
    x = adder();
    printf("x is: %d\n", x);
    return 0;
}
---- 

Suppose that compiling the above program results in the following assembly 
instructions (x86_64)

[source]
----
0000000000001149 <assign>:
    114d: 55                    push   %rbp
    114e: 48 89 e5              mov    %rsp,%rbp
    1151: c7 45 fc 28 00 00 00  movl   $0x28,-0x4(%rbp)
    1158: 8b 45 fc              mov    -0x4(%rbp),%eax
    115b: 5d                    pop    %rbp
    115c: c3                    retq

000000000000115d <adder>:
    1161: 55                    push   %rbp
    1162: 48 89 e5              mov    %rsp,%rbp
    1165: 8b 45 fc              mov    -0x4(%rbp),%eax
    1168: 83 c0 02              add    $0x2,%eax
    116b: 5d                    pop    %rbp
    116c: c3                    retq

000000000000116d <main>:
    1171: 55                    push   %rbp
    1172: 48 89 e5              mov    %rsp,%rbp
    1175: 48 83 ec 10           sub    $0x10,%rsp
    1179: e8 cb ff ff ff        callq  1149 <assign>
    117e: e8 da ff ff ff        callq  115d <adder>
    1183: 89 45 fc              mov    %eax,-0x4(%rbp)
    1186: 8b 45 fc              mov    -0x4(%rbp),%eax
    1189: 89 c6                 mov    %eax,%esi
    118b: 48 8d 3d 72 0e 00 00  lea    0xe72(%rip),%rdi     
    1192: b8 00 00 00 00        mov    $0x0,%eax
    1197: e8 b4 fe ff ff        callq  1050 <printf@plt>
    119c: b8 00 00 00 00        mov    $0x0,%eax
    11a1: c9                    leaveq
    11a2: c3                    retq
----

NOTE: In _The Hitchhiker's Guide to the Galaxy_ by Douglas Adams, the "Answer to the
Ultimate Question of Life, the Universe, and Everything," calculated by an
enormous supercomputer named Deep Thought over a period of 7.5 million years.

++++
<div class="pagebreak"></div>
++++

1) Suppose this is the state of the stack immediately prior to executing `main`
Please show the before and after state (cross out old values).

[source]
----
000000000000116d <main>:
--> 1171: 55                    push   %rbp
    1172: 48 89 e5              mov    %rsp,%rbp
    1175: 48 83 ec 10           sub    $0x10,%rsp
    1179: e8 cb ff ff ff        callq  1149 <assign>
    117e: e8 da ff ff ff        callq  115d <adder>
    1183: 89 45 fc              mov    %eax,-0x4(%rbp)
    1186: 8b 45 fc              mov    -0x4(%rbp),%eax
    1189: 89 c6                 mov    %eax,%esi
----

[cols="1a,4a"]
|===
|
[cols="1,1"]
!===
!Register ! Value
!%eax ! 379
!%edi ! 1
!%rsp ! 0xe68
!%rbp  ! 0x1578
!%rip  ! 0x1171
!===
| 
"Stack top"
[cols="1,4"]
!===
!Address ! Stack value
!{nbsp} + ! 
!{nbsp} + ! 
!{nbsp} + ! 
!{nbsp} + ! 
!{nbsp} + ! 
!{nbsp} + ! 
!{nbsp} +  ! 
!0xe68  ! 
!===
|===
++++
<div class="pagebreak"></div>
++++

2) What are the contents of registers and the stack after executing `mov %rsp, %rbp`?
Please show the before and after state (cross out old values).

[source]
----
000000000000116d <main>:
    1171: 55                    push   %rbp
--> 1172: 48 89 e5              mov    %rsp,%rbp
    1175: 48 83 ec 10           sub    $0x10,%rsp
    1179: e8 cb ff ff ff        callq  1149 <assign>
    117e: e8 da ff ff ff        callq  115d <adder>
    1183: 89 45 fc              mov    %eax,-0x4(%rbp)
    1186: 8b 45 fc              mov    -0x4(%rbp),%eax
    1189: 89 c6                 mov    %eax,%esi
----

[cols="1a,4a"]
|===
|
[cols="1,1"]
!===
!Register ! Value
!%eax ! 
!%edi ! 
!%rsp ! 
!%rbp  ! 
!%rip  ! 
!===
| 
"Stack top"
[cols="1,4"]
!===
!Address ! Stack value
!{nbsp} + ! 
!{nbsp} + ! 
!{nbsp} + ! 
!{nbsp} + ! 
!{nbsp} + ! 
!{nbsp} + ! 
!{nbsp} +  ! 
!0xe68  ! 
!===
|===
++++
<div class="pagebreak"></div>
++++

3) What is the state of registers and the stack after executing `sub $0x10, %rsp`?
Please show the before and after state (cross out old values).

[source]
----
000000000000116d <main>:
    1171: 55                    push   %rbp
    1172: 48 89 e5              mov    %rsp,%rbp
--> 1175: 48 83 ec 10           sub    $0x10,%rsp
    1179: e8 cb ff ff ff        callq  1149 <assign>
    117e: e8 da ff ff ff        callq  115d <adder>
    1183: 89 45 fc              mov    %eax,-0x4(%rbp)
    1186: 8b 45 fc              mov    -0x4(%rbp),%eax
    1189: 89 c6                 mov    %eax,%esi
----

[cols="1a,4a"]
|===
|
[cols="1,1"]
!===
!Register ! Value
!%eax ! 
!%edi ! 
!%rsp ! 
!%rbp  ! 
!%rip  ! 
!===
| 
"Stack top"
[cols="1,4"]
!===
!Address ! Stack value
!{nbsp} + ! 
!{nbsp} + ! 
!{nbsp} + ! 
!{nbsp} + ! 
!{nbsp} + ! 
!{nbsp} + ! 
!{nbsp} +  ! 
!0xe68  ! 
!===
|===
++++
<div class="pagebreak"></div>
++++

4) What is the state of registers and the stack after executing `callq 0x1149 <assign>`?
Please show the before and after state (cross out old values).

[source]
----
000000000000116d <main>:
    1171: 55                    push   %rbp
    1172: 48 89 e5              mov    %rsp,%rbp
    1175: 48 83 ec 10           sub    $0x10,%rsp
--> 1179: e8 cb ff ff ff        callq  1149 <assign>
    117e: e8 da ff ff ff        callq  115d <adder>
    1183: 89 45 fc              mov    %eax,-0x4(%rbp)
    1186: 8b 45 fc              mov    -0x4(%rbp),%eax
    1189: 89 c6                 mov    %eax,%esi
----

[cols="1a,4a"]
|===
|
[cols="1,1"]
!===
!Register ! Value
!%eax ! 
!%edi ! 
!%rsp ! 
!%rbp  ! 
!%rip  ! 
!===
| 
"Stack top"
[cols="1,4"]
!===
!Address ! Stack value
!{nbsp} + ! 
!{nbsp} + ! 
!{nbsp} + ! 
!{nbsp} + ! 
!{nbsp} + ! 
!{nbsp} + ! 
!{nbsp} +  ! 
!0xe68  ! 
!===
|===
++++
<div class="pagebreak"></div>
++++

5) Skipping ahead, what is the state of registers and the stack when the program executes `pop %rbp`?
What two changes occur during `pop`?
Please show the before and after state (cross out old values).

[source]
----
0000000000001149 <assign>:
    114d: 55                    push   %rbp
    114e: 48 89 e5              mov    %rsp,%rbp
    1151: c7 45 fc 28 00 00 00  movl   $0x28,-0x4(%rbp)
    1158: 8b 45 fc              mov    -0x4(%rbp),%eax
--> 115b: 5d                    pop    %rbp
    115c: c3                    retq
----

[cols="1a,4a"]
|===
|
[cols="1,1"]
!===
!Register ! Value
!%eax ! 
!%edi ! 
!%rsp ! 
!%rbp  ! 
!%rip  ! 
!===
| 
"Stack top"
[cols="1,4"]
!===
!Address ! Stack value
!{nbsp} + ! 
!{nbsp} + ! 
!{nbsp} + ! 
!{nbsp} + ! 
!{nbsp} + ! 
!{nbsp} + ! 
!{nbsp} +  ! 
!0xe68  ! 
!===
|===
++++
<div class="pagebreak"></div>
++++

6) What is the state of registers and the stack after executing `retq`?
Please show the before and after state (cross out old values).

[source]
----
0000000000001149 <assign>:
    114d: 55                    push   %rbp
    114e: 48 89 e5              mov    %rsp,%rbp
    1151: c7 45 fc 28 00 00 00  movl   $0x28,-0x4(%rbp)
    1158: 8b 45 fc              mov    -0x4(%rbp),%eax
    115b: 5d                    pop    %rbp
--> 115c: c3                    retq
----

[cols="1a,4a"]
|===
|
[cols="1,1"]
!===
!Register ! Value
!%eax ! 
!%edi ! 
!%rsp ! 
!%rbp  ! 
!%rip  ! 
!===
| 
"Stack top"
[cols="1,4"]
!===
!Address ! Stack value
!{nbsp} + ! 
!{nbsp} + ! 
!{nbsp} + ! 
!{nbsp} + ! 
!{nbsp} + ! 
!{nbsp} + ! 
!{nbsp} +  ! 
!0xe68  ! 
!===
|===
++++
<div class="pagebreak"></div>
++++

7) Skipping ahead, what are the state of registers and the stack when executing `retq` in adder?
Please show the before and after state (cross out old values).

[source]
----
000000000000115d <adder>:
    1161: 55                    push   %rbp
    1162: 48 89 e5              mov    %rsp,%rbp
    1165: 8b 45 fc              mov    -0x4(%rbp),%eax
    1168: 83 c0 02              add    $0x2,%eax
    116b: 5d                    pop    %rbp
--> 116c: c3                    retq
----

[cols="1a,4a"]
|===
|
[cols="1,1"]
!===
!Register ! Value
!%eax ! 
!%edi ! 
!%rsp ! 
!%rbp  ! 
!%rip  ! 
!===
| 
"Stack top"
[cols="1,4"]
!===
!Address ! Stack value
!{nbsp} + ! 
!{nbsp} + ! 
!{nbsp} + ! 
!{nbsp} + ! 
!{nbsp} + ! 
!{nbsp} + ! 
!{nbsp} +  ! 
!0xe68  ! 
!===
|===

8) Consider the call the printf, `callq 1050 <printf@plt>`. The previous lines place the first 
argument to printf into `%rdi`. Assume this contains "x is %d\n". The second argument will be 
placed in `%esi`. What value will %esi containin?

[source]
----
000000000000116d <main>:
    1171: 55                    push   %rbp
    1172: 48 89 e5              mov    %rsp,%rbp
    1175: 48 83 ec 10           sub    $0x10,%rsp
    1179: e8 cb ff ff ff        callq  1149 <assign>
    117e: e8 da ff ff ff        callq  115d <adder>
    1183: 89 45 fc              mov    %eax,-0x4(%rbp)
    1186: 8b 45 fc              mov    -0x4(%rbp),%eax
    1189: 89 c6                 mov    %eax,%esi
    118b: 48 8d 3d 72 0e 00 00  lea    0xe72(%rip),%rdi
    1192: b8 00 00 00 00        mov    $0x0,%eax
    1197: e8 b4 fe ff ff        callq  1050 <printf@plt>
    119c: b8 00 00 00 00        mov    $0x0,%eax
    11a1: c9                    leaveq
    11a2: c3                    retq
----
