include::header.adoc[]

:title: Assignment 6: MyEditor Part 2
:Author Initials: ASN
:Date:    2020-08-15
:Revision: 0.1
:ASST: A06

= {title}

**Due Friday, February 27, before midnight**

The goals for this assignment are:

* Work with pointer-based data structures
* Strengthen C programming with strings and files

:sectnums:

= Update your repository

This assignment uses the same basecode as last week (folder {ASST}).

= Editor

In the file, `myeditor.c`, implement the following features.

* Pressing 'i' should go into edit mode and allow the user to edit the current line. 
* Save the file with ':w'

= Spell checker

In the file, `myeditor.c`, implement a feature that highlights misspelled words. Your solution should 

* Load the file `dictionary` into a large array of strings. Each row contains a single word, already in alphabetical order. You may hard-code the number of strings in the file.
* Implement a function that uses binary search to check the spelling of each word in the loaded file.
* Using the ncurses library, highlight misspelled words with either colors or a stylistic effect.

= Choose your own adventure

Choose two more Vim feature of your choice to implement. Below are some ideas.
Be sure to document which features you implement, either in a README file or in a header comment! 

* Show line numbers 
* Goto line with the command ':<linenum>'
* 'Y' to copy a line
* 'dd' to delete a line
* 'x' to delete a character
* 'I' to insert characters at the beginning of the line
* 'A' to append characters at the end of the line
* 'G' to go to the end of the file
* Show a welcome screen before editing
* Support creating new files
* Show the number of lines in the file in the banner bar
* Searching with '/', 'n', and 'p'. 
* etc!

= Submit your work

Push you work to github to submit your work.

[source]
----
$ cd {ASST}
$ git status
$ git add *.c 
$ git status
$ git commit -m "assignment complete"
$ git status
$ git push
$ git status
----

= Grading Rubric

*Assignment rubrics*

Grades are out of 4 points.

* (2 points) matched braces
** (0.2 points) style and header comment
** (0.8 points) correct output and behavior, supports command line arguments
** (1.0 points) no memory errors
* (1 points) Tree
** (0.1 points) style and header comment
** (0.4 points) implements all functions, passes all tests and does not modify basecode
** (0.5 points) no memory errors
* (1 points) Dependencies
** (0.1 points) style and header comment
** (0.4 points) Correct behavior
** (0.5 points) no memory errors

*Code rubrics*

For full credit, your C programs must be feature-complete, robust (e.g. run without memory errors or crashing) and 
have good style.

* Some credit lost for missing features or bugs, depending on severity of error
* -5% for style errors. See the link:../codingstandard.html[class coding style] here.
* -50% for memory errors
* -100% for failure to checkin work to Github
* -100% for failure to compile on linux using make
